-- ═══════════════════════════════════════════════════════════════════════════
-- VTIS 2026 — Supabase Schema
-- Run this entire file in the Supabase SQL Editor (Dashboard → SQL Editor)
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Extension for UUID generation ─────────────────────────────────────────
create extension if not exists "pgcrypto";

-- ── 2. Registrations table ────────────────────────────────────────────────────
create table if not exists public.registrations (
  -- Internal primary key (UUID, never exposed publicly)
  id                uuid        primary key default gen_random_uuid(),

  -- Public-facing sequential registration number (VTIS 01, VTIS 02, …)
  -- Generated by the trigger below — never set manually
  registration_number integer    unique not null,
  registration_id     text       unique not null generated always as (
    'VTIS ' || lpad(registration_number::text, 2, '0')
  ) stored,

  -- Participant details
  first_name          text       not null,
  last_name           text       not null,
  email               text       not null unique,
  profile             text       not null,

  -- Days attending (booleans)
  day1                boolean    not null default false,
  day2                boolean    not null default false,
  day3                boolean    not null default false,

  -- Timestamps
  registered_at       timestamptz not null default now(),

  -- Ticket & email status
  ticket_generated    boolean    not null default false,
  ticket_url          text,
  email_sent          boolean    not null default false,
  email_sent_at       timestamptz,
  email_error         text,

  -- Check-in
  checked_in          boolean    not null default false,
  checked_in_at       timestamptz
);

-- ── 3. Sequence for registration_number ──────────────────────────────────────
-- Uses a dedicated sequence so concurrent inserts never collide.
create sequence if not exists public.vtis_registration_seq start 1;

create or replace function public.set_registration_number()
returns trigger
language plpgsql
as $$
begin
  -- nextval is atomic — concurrent transactions each get a unique value
  new.registration_number := nextval('public.vtis_registration_seq');
  return new;
end;
$$;

create trigger trg_set_registration_number
  before insert on public.registrations
  for each row
  execute function public.set_registration_number();

-- ── 4. Indexes ────────────────────────────────────────────────────────────────
create index if not exists idx_registrations_email          on public.registrations (email);
create index if not exists idx_registrations_reg_id         on public.registrations (registration_id);
create index if not exists idx_registrations_registered_at  on public.registrations (registered_at desc);
create index if not exists idx_registrations_checked_in     on public.registrations (checked_in);

-- ── 5. Row-Level Security ─────────────────────────────────────────────────────
-- Public: no direct read/write (all access goes through the backend service key)
alter table public.registrations enable row level security;

-- Backend uses the SERVICE ROLE key which bypasses RLS automatically.
-- Optionally add an admin policy here if you use Supabase Auth for the admin portal.

-- ── 6. Admin users table (for admin portal login) ─────────────────────────────
create table if not exists public.admin_users (
  id           uuid    primary key default gen_random_uuid(),
  email        text    not null unique,
  -- Passwords are hashed with bcrypt BEFORE inserting — never store plaintext
  password_hash text   not null,
  name         text    not null,
  created_at   timestamptz not null default now(),
  last_login   timestamptz
);

alter table public.admin_users enable row level security;

-- ── 7. Helpful view for admin dashboard ──────────────────────────────────────
create or replace view public.admin_registration_view as
select
  registration_id,
  first_name || ' ' || last_name  as full_name,
  email,
  profile,
  case
    when day1 and day2 and day3 then 'All 3 Days'
    when day1 and day2          then 'Day 1 + Day 2'
    when day1 and day3          then 'Day 1 + Day 3'
    when day2 and day3          then 'Day 2 + Day 3'
    when day1                   then 'Day 1 Only'
    when day2                   then 'Day 2 Only'
    when day3                   then 'Day 3 Only'
    else                             'None Selected'
  end                             as days_attending,
  registered_at,
  ticket_generated,
  email_sent,
  checked_in,
  checked_in_at
from public.registrations
order by registration_number asc;
